[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Dismonder"
name = "AgeOfJarls"
versionNumber = "0.7.2"
description = "Found settlements, rescue settlers and let them work and fight for you. Co-op, existing worlds."
websiteUrl = "https://github.com/Dismonder/AgeOfJarls"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2350"
ValheimModding-Jotunn = "2.30.0"

[build]
icon = "mods/AgeOfJarls/Package/icon.png"
readme = "mods/AgeOfJarls/Package/README.md"
outdir = "dist"

[publish]
communities = ["valheim"]

[publish.categories]
valheim = ["mods", "npcs", "building", "crafting", "server-side", "deep-north-update"]


